# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
  # adresse IPv6 avec nmcli (CLI pour NetworkManager)
  # éventuellement, pour supprimer les connexions en trop, faire
  # $ nmcli connection del ansible-eth1
#   - shell: ip -6 route delete default
   #Instalation du DHCPv6
#- copy: src="/vagrant/radvd.conf" dest="/etc/radvd.conf" owner=root group=root mode=644
#- apt: name=radvd state=latest
   #Routing
   - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip6 fc00:1234:1::2/64
   - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::2/64
   - shell: sysctl -w net.ipv6.conf.all.forwarding=1
   #Init du DHCP
#- service: name=radvd state=started
#- service: name=radvd state=stopped
#- service: name=radvd state=started
